### ISSUE TITLE
choose first good issues to tackle on

### ISSUE THREAD

**Issue by MatoPlus** [team-vibe-labs/blockly#3]
https://github.com/google/blockly-samples/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

**Comment by d-projects** [comment]
All seven of the below look like good first issues (will require changes on 2-4 files):
1) https://github.com/google/blockly-samples/issues/1247
2) https://github.com/google/blockly-samples/issues/1246
3) https://github.com/google/blockly-samples/issues/1245
4) https://github.com/google/blockly-samples/issues/1243
5) https://github.com/google/blockly-samples/issues/1255
6) https://github.com/google/blockly-samples/issues/1253
7) https://github.com/google/blockly-samples/issues/1251

**Comment by d-projects** [comment]
Number 5 seems to require the least XML to JSON conversion, so that could be a good starting one. All the others seems to have a similar amount of conversion work.
